/* eslint-disable @typescript-eslint/no-explicit-any */
/**
 * This file is auto-generated by env-auto. It provides a runtime typed wrapper for process.env.
 * Do not edit - changes will be overwritten.
 */
/// <reference types="node" />

export const nomad = {
  NEXT_PUBLIC_BASE_API_URL: process.env['NEXT_PUBLIC_BASE_API_URL'] as any,
  JWT_ACCESS_SECRET: process.env['JWT_ACCESS_SECRET'] as any,
} as const;
